### ISSUE TITLE
Insight tool tip documentations

### ISSUE THREAD

**Issue by thinhpham2122** [JIE-1350/ISpy#49]
Each insight should have a tool tip explaining details about the insight.

**Comment by jcarpenter48** [comment]
Tooltips:
Sentiment Analysis:
Each Tweet's sentiment is calculated using NLTK VADER Sentiment Intensity Analyzer
Scores range from -1.0 (completely negative) to 1.0 (complete positive sentiment)
The numbers of negative, neutral, and positive tweets and averaged sentiment score are shown

Influence Score:
Provides average replies, retweets, and likes count for tweets in dataset, as well as averaged composite 'influence' score
This gives a quick feel in absolute numbers of the reach of the subject or user

Tweet Frequency:
Graphs the count of relevant tweets (on subject, by user, etc.) made over the given period of time.

Top Hashtags:
Most common Hashtags in the dataset are counted and both listed and graphed to see relative popularity

Time of Tweets:
Maps tweet times to hours of a day and graphs count of tweets for each hour

**Comment by thinhpham2122** [comment]
![image.png](https://images.zenhubusercontent.com/61dc9675a8ade530265d21b7/d8508d48-4376-4455-9349-b2d72d02ce5b)
