### ISSUE TITLE
Detailed Design - UI Design

### ISSUE THREAD

**Issue by thinhpham2122** [JIE-1350/ISpy#52]
https://gatech.instructure.com/courses/232984/pages/detailed-design-ui-design

**Comment by thaott1901** [comment]
![search](https://user-images.githubusercontent.com/79027214/162494207-317f859b-9ab3-4fac-bdbb-8020a33e9211.png)
![insights](https://user-images.githubusercontent.com/79027214/162494199-a123c2e2-930b-4812-8393-f8e333a06f14.png)
