### ISSUE TITLE
Expo Elevator Pitch Presentation

### ISSUE THREAD

**Issue by thinhpham2122** [JIE-1350/ISpy#54]
Prepare elevator pitch for the demo, and record a video giving the elevator pitch.

**Comment by jcarpenter48** [comment]
**Elevator Pitch Script:**
“Normally, if someone wants to collect Twitter data to conduct research, they either manually collect that data, or write their own tools to collect data. Very complex, time consuming, and tedious! Same for Analysis! What our tool, Intelligent Scraping with Python, does, simplifies the entire process, end to end, turning data collection and analysis into a process as simple as a Google search, greatly expediting Twitter-based social or market research." + "Let’s take a look.” [begin demo]
